include:
  - board: seeeduino_xiao_ble
    shield: Enigma_01 rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: Enigma_01_a
    
  - board: seeeduino_xiao_ble
    shield: Enigma_01 rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: Enigma_01_b
    
  - board: seeeduino_xiao_ble
    shield: Enigma_01 rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: Enigma_01_c
